Feat/sigmas 197  turnoff csp report
signify-nz/silverstripe-security-headers pull request #6
Opened 2021-08-19 06:06 UTC by sig-michelle

Add another three setting options in the CMS:
- Enable Content Security Policy with reporting (recommended)
- Set Content Security Policy to report-only mode
- Enable Content Security Policy without reporting
- Disable Content Security Policy (not recommended)

Added functions to support the new options, and updated the documents.
Ticket: SIGMAS-197

2021-08-20 03:35 UTC, GuySartorelli requested changes
A few changes to make. Once these changes are made I'll check the module in my scratch site to ensure it's all working as expected.

2021-08-20 03:35 UTC, GuySartorelli commented on docs/en/00_index.md
>  - [Content Security Policy Violations Report](02_csp-report.md)
That documentation is no longer exclusively about the CSP violations report, since it includes settings to disable CSP altogether. Please rename this (including the file name), e.g.:
[Content Security Policy Options](02_csp.md)

2021-08-20 03:35 UTC, GuySartorelli commented on docs/en/02_csp-report.md
> +## Setting options
Now that there are more options than just for reporting, the main heading for this file needs to be changed. It should be the same change you're making in 00_index.md

2021-08-20 03:35 UTC, GuySartorelli commented on docs/en/02_csp-report.md
> +- Set Content Security Policy to report-only mode. This gives you the option to set the Content Security Policy to report only mode (this swaps from using the `Content-Security-Policy` header to the
These should be in the order outlined in SIGMAS-197. The order in that ticket is from most to least secure.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Extensions/SecurityHeaderSiteconfigExtension.php
> +    private static $defaults = [
Remove this array - Enum's default value is always the first value in the enum, so 0 is already the default anyway.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Extensions/SecurityHeaderSiteconfigExtension.php
> +                    '0' => 'Enable Content Security Policy with reporting (recommended)',
These should be in the order outlined in SIGMAS-197. The order in that ticket is from most to least secure.
I know this would mean the value order would be 0, 2, 1, 3 but that's absolutely fine.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Extensions/SecurityHeaderSiteconfigExtension.php
> +        "CSPReportingOnly" => "Enum('0,1,2,3')",
Add constants for each of the options.
e.g.
```php
// The values are in this order to ensure backwards compatability with the old binary options.
public const CSP_WITH_REPORTING = 0;
public const CSP_WITHOUT_REPORTING = 2;
public const CSP_REPORTING_ONLY = 1;
public const CSP_DISABLE = 3;
```

2021-08-20 03:35 UTC, GuySartorelli commented on src/Extensions/SecurityHeaderSiteconfigExtension.php
> +                    '0' => 'Enable Content Security Policy with reporting (recommended)',
Use the constants mentioned above here instead of specifically '0', '1', etc.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '3') {
Use the constant from the SecurityHeaderSiteconfigExtension class instead of '3'. It makes it a lot clearer what is happening.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '2') {
Use the constant from the SecurityHeaderSiteconfigExtension class instead of '2'. It makes it a lot clearer what is happening.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (self::isCSPReportingOnlyAvailable() && SiteConfig::current_site_config()->CSPReportingOnly == '1') {
Use the constant from the SecurityHeaderSiteconfigExtension class instead of '1'. It makes it a lot clearer what is happening.

2021-08-20 03:35 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +            $this->config()->set('enable_reporting', false);
Do not manipulate the config this way. Instead, add `!$this->disableReporting()` to the if statement in line 98.

2021-08-20 03:48 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '2') {
This should probably also include self::isCSPReportingOnlyAvailable(), e.g:
```php
return SiteConfig::current_site_config()->CSPReportingOnly == SecurityHeaderSiteconfigExtension::CSP_WITHOUT_REPORTING && $this->config()->get('enable_reporting')
```

2021-08-20 04:01 UTC, sig-michelle commented on src/Middleware/SecurityHeaderMiddleware.php
> +            $this->config()->set('enable_reporting', false);
What's do you mean by this one?

2021-08-20 06:47 UTC, sig-michelle commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '2') {
The 'enable_reporting' can be removed from the config, as the CMS has added the same option.
Setting: Enable Content Security Policy without reporting

2021-08-20 09:06 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '2') {
My snippet was wrong - it should be 
```php
return SiteConfig::current_site_config()->CSPReportingOnly == SecurityHeaderSiteconfigExtension::CSP_WITHOUT_REPORTING || !$this->config()->get('enable_reporting')
```
In other words, reporting is disabled if it's disabled in the CMS _OR_ disabled via config. So even if `enable_reporting` is true, setting the CMS setting will still disable reporting.

2021-08-20 09:09 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '3') {
You'll also need to check (And rename) `self::isCSPReportingOnlyAvailable()`

2021-08-20 09:09 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +        if (SiteConfig::current_site_config()->CSPReportingOnly == '2') {
You'll also need to check (And rename) `self::isCSPReportingOnlyAvailable()`

2021-08-25 00:13 UTC, GuySartorelli requested changes
Just one thing to change that I missed the first time around.

2021-08-25 00:13 UTC, GuySartorelli commented on src/Middleware/SecurityHeaderMiddleware.php
> +            return $response;
I didn't catch this is the last review - but this is actually going to disable ALL SECURITY HEADERS, not just the CSP.

Instead of this, you should be removing the `Content-Security-Policy` key from the `$headersToSend` array if it's present. The check for that is in line 98 so it should happen somewhere in there.

2021-08-25 04:34 UTC, GuySartorelli approved these changes

2021-08-25 04:45 UTC, merged

2021-10-05 01:58 UTC, sig-michelle commented on src/Middleware/SecurityHeaderMiddleware.php
> +
The second line is too long. Build info: https://app.travis-ci.com/github/signify-nz/silverstripe-security-headers/jobs/541263716
149 | WARNING | Line exceeds 120 characters; contains 130 characters

2021-10-05 02:53 UTC, sig-steve commented on src/Middleware/SecurityHeaderMiddleware.php
> +
Then reformat it to fit.

```php
        if (self::isCSPReportingAvailable()) {
            return SiteConfig::current_site_config()->CSPReportingOnly 
                == SecurityHeaderSiteconfigExtension::CSP_WITHOUT_REPORTING
                || !$this->config()->get('enable_reporting');
        }
```